const ActionTypes = {
  AUTH: {
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT",
  },
  MODALS: {
    SHOW_MOBILE_MAP: "SHOW_MOBILE_MAP",
    CLOSE_MOBILE_MAP: "CLOSE_MOBILE_MAP",
    SHOW_MENU_MODAL: "SHOW_MENU_MODAL",
    CLOSE_MENU_MODAL: "CLOSE_MENU_MODAL",
    SHOW_AUTH_MODAL: "SHOW_AUTH_MODAL",
    CLOSE_AUTH_MODAL: "CLOSE_AUTH_MODAL",
    SHOW_REGISTER_MODAL: "SHOW_REGISTER_MODAL",
    CLOSE_REGISTER_MODAL: "CLOSE_REGISTER_MODAL",
  },
};

export default ActionTypes;
